name: Humanely
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  permission_handler: ^5.0.1
  shared_preferences: ^0.5.7+3
  flutter_screenutil: ^2.1.0
  modal_progress_hud: ^0.1.3
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  provider: ^4.1.3
  android_intent: ^0.3.7+2
  package_info: '>=0.4.0+14 <2.0.0'
  location: ^3.0.2
  google_maps_webservice: ^0.0.16
  tuple: ^1.0.3
  geocoder: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/map/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: font/Poppins-Regular.ttf
        - asset: font/Poppins-Light.ttf

  uses-material-design: true
