name: Humanely
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  permission_handler: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: font/Poppins-Regular.ttf
        - asset: font/Poppins-Light.ttf

  uses-material-design: true
